[connection:core1]
host: 172.20.20.102
transport: http
username: admin
password: admin

[connection:access1]
host: 172.20.20.103
transport: http
username: admin
password: admin

[connection:access2]
host: 172.20.20.104
transport: http
username: admin
password: admin

[connection:access3]
host: 172.20.20.105
transport: http
username: admin
password: admin