interfaces:
  - id: 'eth1'
    name: 'Ethernet1'
    ipv4: 10.0.0.2/30
    vlan: 1

  - id: 'eth2'
    name: 'Ethernet2'
    ipv4: '10.0.0.14/30'
    vlan: 1

  - id: 'eth10'
    name: 'Ethernet10'
    vlan: '100'
    
  - id: 'eth11'
    name: 'Ethernet11'
    vlan: '101'