all:
  children:
    arista_nodes:
      hosts:
        spine1:
          ansible_host: 172.20.20.101
        spine2:
          ansible_host: 172.20.20.102
        leaf1:
          ansible_host: 172.20.20.103
        leaf2:
          ansible_host: 172.20.20.104
        leaf3:
          ansible_host: 172.20.20.105
  vars:
    admin_user: admin
    admin_password: admin
    ansible_netowrk_os: arista.eos.eos
    ansible_connection: httpapi

    ansible_become: true
    ansible_become_method: enable
