---
- name: controller
  hosts: leaf
  gather_facts: false

  tasks:
  - name: config vlan
    arista.eos.eos_config:
      lines:
        - vlan 10
        # - intterface {{ item.name }}
        # - switchport mode access
        # - switchport access vlan {{ item.vlan }}
    # loop: "{{ interfaces }}"